name = "feature-toggle"
compatibility_date = "2024-01-15"
pages_build_output_dir = "out"

[env.production]
name = "feature-toggle-prod"

[env.staging]
name = "feature-toggle-staging"

[[env.production.vars]]
DATABASE_URL = ""
NEXTAUTH_URL = ""
NEXTAUTH_SECRET = ""
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GITHUB_ID = ""
GITHUB_SECRET = ""