blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/pradiktabagus/feature-toggle/tree/main/documentation
    about: Check our comprehensive documentation before creating an issue
  - name: 💬 Discussions
    url: https://github.com/pradiktabagus/feature-toggle/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🚀 Project Roadmap
    url: https://github.com/pradiktabagus/feature-toggle/blob/main/blueprint.md
    about: View our development roadmap and planned features