name: PR Automation

on:
  pull_request:
    types: [opened]

jobs:
  process-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Process new PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || '';
            
            console.log(`Processing PR #${pr.number}: ${pr.title}`);
            
            // Add project board comment
            const projectUrl = 'https://github.com/users/pradiktabagus/projects/5';
            const message = `🚀 This pull request has been created! Please add it to the [project board](${projectUrl}) manually.
            
**PR Details:**
- Branch: \`${pr.head.ref}\`
- Base: \`${pr.base.ref}\`
- Files changed: ${pr.changed_files}
- Additions: +${pr.additions}
- Deletions: -${pr.deletions}

**Next steps:**
1. Add to project board "In Progress" column
2. Request code review
3. Link to related issue if applicable
4. Ensure all checks pass before merge`;
            
            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: message
              });
              console.log('Successfully added project comment to PR');
            } catch (error) {
              console.log('Error adding comment to PR:', error.message);
            }