name: Simple CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build job running"
      
  lint:
    runs-on: ubuntu-latest  
    steps:
      - run: echo "Lint job running"
      
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test job running"